# Generated by Django 4.1.1 on 2022-12-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametre',
        ),
    ]
