# Generated by Django 4.1.1 on 2022-12-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='id_secteuragricole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametre',
            name='id_secteurfemmeactive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametre',
            name='id_secteurinformel',
            field=models.IntegerField(default=0),
        ),
    ]
