# Generated by Django 4.1.1 on 2022-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_parametre_id_secteuragricole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='id_accident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametre',
            name='id_deces',
            field=models.IntegerField(default=0),
        ),
    ]
