# Generated by Django 4.1.1 on 2022-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destinateurs',
            field=models.ManyToManyField(related_name='destinateurs_message', to='test_app.personne'),
        ),
    ]
