# Generated by Django 4.1.1 on 2022-10-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etatcivil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=250, unique=True, verbose_name='Niveau')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=250, unique=True, verbose_name='Classe')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatcivil.niveau')),
            ],
        ),
    ]
