# Generated by Django 4.1.1 on 2022-10-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etatcivil', '0002_niveau_niveauscolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
            ],
        ),
        migrations.AlterField(
            model_name='niveauscolaire',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.niveau'),
        ),
    ]
