# Generated by Django 4.1.1 on 2022-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etatcivil', '0003_sexe_alter_niveauscolaire_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('nationalite', models.CharField(max_length=100, unique=True, verbose_name='Nationalité')),
                ('pays', models.CharField(max_length=250, unique=True, verbose_name='Pays')),
            ],
        ),
    ]
