# Generated by Django 4.1.1 on 2022-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etatcivil', '0004_nationalite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationMatrimoniale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
