# Generated by Django 4.1.1 on 2022-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='libelle',
            field=models.CharField(max_length=150, unique=True, verbose_name='Libellé'),
        ),
    ]
