# Generated by Django 4.1.1 on 2022-10-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0005_rename_district_departement_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='libelle',
            field=models.CharField(max_length=250, unique=True, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='district',
            name='libelle',
            field=models.CharField(max_length=250, unique=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='region',
            name='libelle',
            field=models.CharField(max_length=250, unique=True, verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=250, unique=True, verbose_name='Ville')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.departement')),
            ],
        ),
    ]
