# Generated by Django 4.1.1 on 2022-10-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0006_alter_departement_libelle_alter_district_libelle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='region',
            new_name='departement',
        ),
    ]
