# Generated by Django 4.1.1 on 2022-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0003_secteur_typesecteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SecteurInformel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_adhesion', models.DateField(auto_now=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True)),
                ('metier', models.CharField(max_length=250, verbose_name='Métier')),
                ('membre', models.ManyToManyField(to='vieprofessionnelle.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecteurFemmeActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_adhesion', models.DateField(auto_now=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True)),
                ('personne_ressource', models.ManyToManyField(to='vieprofessionnelle.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecteurAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_adhesion', models.DateField(auto_now=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True)),
                ('speculation_agricole', models.IntegerField(verbose_name='Spéculation agricole')),
                ('superficie_en_culture', models.IntegerField(verbose_name='Superficie en culture')),
                ('superficie_en_production', models.IntegerField(verbose_name='Superficie en production')),
                ('gps_longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Longitude')),
                ('gps_latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Latitude')),
                ('membre', models.ManyToManyField(to='vieprofessionnelle.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
