# Generated by Django 4.1.1 on 2022-11-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0004_membre_secteurinformel_secteurfemmeactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secteuragricole',
            old_name='membre',
            new_name='membres',
        ),
        migrations.RenameField(
            model_name='secteurinformel',
            old_name='membre',
            new_name='membres',
        ),
    ]
