# Generated by Django 4.1.1 on 2022-11-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0006_secteurfemmeactive_membres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomprenoms', models.CharField(max_length=250, verbose_name='Nom et prénoms')),
                ('datenaissance', models.DateField(verbose_name='Date de naissance')),
                ('typeparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.typeparent')),
            ],
        ),
    ]
