# Generated by Django 4.1.1 on 2022-11-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0008_alter_parent_datenaissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEtatSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='EtatSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateenre', models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement")),
                ('typeetatsante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.typeetatsante')),
                ('typeparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.typeparent')),
            ],
        ),
    ]
