# Generated by Django 4.1.1 on 2022-11-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0009_typeetatsante_etatsante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatsante',
            name='typeparent',
        ),
        migrations.AddField(
            model_name='etatsante',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.parent'),
        ),
    ]
