# Generated by Django 4.1.1 on 2022-11-11 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0011_typedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateenre', models.DateField(blank=True, default=datetime.date(2022, 11, 11), null=True, verbose_name="Date d'enregistrement")),
                ('membre', models.ManyToManyField(to='vieprofessionnelle.membre')),
                ('typedocument', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.typedocument')),
            ],
        ),
    ]
