# Generated by Django 4.1.1 on 2022-11-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0013_alter_document_dateenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='membre',
            new_name='membres',
        ),
        migrations.AlterField(
            model_name='document',
            name='dateenre',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 11, 13, 14, 13, 94277, tzinfo=datetime.timezone.utc), null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
