# Generated by Django 4.1.1 on 2022-11-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0014_rename_membre_document_membres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dateenre',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 11, 13, 14, 41, 169918, tzinfo=datetime.timezone.utc), null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
