# Generated by Django 4.1.1 on 2022-11-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_marche'),
        ('etatcivil', '0005_situationmatrimoniale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vieprofessionnelle', '0022_alter_document_dateenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='dateenre',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='membre',
            name='nationalite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.nationalite'),
        ),
        migrations.AddField(
            model_name='membre',
            name='niveauscolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.niveauscolaire'),
        ),
        migrations.AddField(
            model_name='membre',
            name='numerobadge',
            field=models.CharField(default='', max_length=250, verbose_name='N°Badge'),
        ),
        migrations.AddField(
            model_name='membre',
            name='parents',
            field=models.ManyToManyField(to='vieprofessionnelle.parent'),
        ),
        migrations.AddField(
            model_name='membre',
            name='prenoms',
            field=models.CharField(default='', max_length=250, verbose_name='Prénoms'),
        ),
        migrations.AddField(
            model_name='membre',
            name='qrcode',
            field=models.CharField(default='', max_length=250, verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='membre',
            name='quartier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.quartier'),
        ),
        migrations.AddField(
            model_name='membre',
            name='secteurs',
            field=models.ManyToManyField(to='vieprofessionnelle.secteur'),
        ),
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.sexe'),
        ),
        migrations.AddField(
            model_name='membre',
            name='situationmatrimoniale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.situationmatrimoniale'),
        ),
        migrations.AddField(
            model_name='membre',
            name='typepiece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etatcivil.typepiece'),
        ),
        migrations.AddField(
            model_name='membre',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateenre',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='Nom'),
        ),
    ]
