# Generated by Django 4.1.1 on 2022-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0023_membre_actif_membre_dateenre_membre_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='membre',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='parent',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='parent',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='secteuragricole',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='secteuragricole',
            name='presidente',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='presidente',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='presidente',
            field=models.CharField(default='', max_length=250),
        ),
    ]
