# Generated by Django 4.1.1 on 2022-11-12 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_marche'),
        ('vieprofessionnelle', '0024_membre_adresse_membre_contact_parent_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='lieunaissance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.commune'),
        ),
        migrations.AddField(
            model_name='membre',
            name='nomjeunefille',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Nom de jeune fille'),
        ),
        migrations.AddField(
            model_name='parent',
            name='dateenre',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 16, 0, 30, 862669, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 16, 0, 30, 862669, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 16, 0, 30, 862669, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numerobadge',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='N°Badge'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='prenoms',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='qrcode',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='date_adhesion',
            field=models.DateField(verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre'),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='presidente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='date_adhesion',
            field=models.DateField(verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre'),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='presidente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='date_adhesion',
            field=models.DateField(verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre'),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='presidente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
