# Generated by Django 4.1.1 on 2022-11-12 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0025_membre_lieunaissance_membre_nomjeunefille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='numeropiece',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='N°de la pièce'),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 20, 28, 39, 746111, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 20, 28, 39, 746111, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 20, 28, 39, 746111, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
    ]
