# Generated by Django 4.1.1 on 2022-11-12 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0026_membre_numeropiece_alter_secteuragricole_dateenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='dateenre',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 22, 23, 47, 589866, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 22, 23, 47, 589866, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 22, 23, 47, 589866, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
    ]
