# Generated by Django 4.1.1 on 2022-11-14 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0027_membre_date_naissance_alter_membre_dateenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='nom_prenoms',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Nom et prénoms'),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 13, 9, 25, 310584, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 13, 9, 25, 310584, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 13, 9, 25, 310584, tzinfo=datetime.timezone.utc), verbose_name="Date d'enregistrement"),
        ),
    ]
