# Generated by Django 4.1.1 on 2022-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0028_membre_nom_prenoms_alter_secteuragricole_dateenre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteuragricole',
            name='date_adhesion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='date_adhesion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='date_adhesion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
