# Generated by Django 4.1.1 on 2022-11-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0029_alter_secteuragricole_date_adhesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteuragricole',
            name='dateenre',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='dateenre',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='dateenre',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
