# Generated by Django 4.1.1 on 2022-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0030_alter_secteuragricole_dateenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Longitude'),
        ),
    ]
