# Generated by Django 4.1.1 on 2022-11-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_marche'),
        ('vieprofessionnelle', '0031_secteurfemmeactive_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.marche'),
        ),
        migrations.AlterField(
            model_name='secteurinformel',
            name='metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.secteur'),
        ),
    ]
