# Generated by Django 4.1.1 on 2022-11-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0033_alter_secteurinformel_metier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteurinformel',
            name='metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.secteur'),
        ),
    ]
