# Generated by Django 4.1.1 on 2022-11-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0034_alter_secteurinformel_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='identifiant',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom_prenoms',
            field=models.CharField(default='', max_length=250, verbose_name='Nom et prénoms'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='qrcode',
            field=models.CharField(default=None, max_length=250, unique=True, verbose_name='QR Code'),
        ),
    ]
