# Generated by Django 4.1.1 on 2022-11-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0036_remove_secteuragricole_membres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteuragricole',
            name='date_adhesion',
        ),
        migrations.RemoveField(
            model_name='secteuragricole',
            name='numero_carte',
        ),
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='date_adhesion',
        ),
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='numero_carte',
        ),
        migrations.RemoveField(
            model_name='secteurinformel',
            name='date_adhesion',
        ),
        migrations.RemoveField(
            model_name='secteurinformel',
            name='numero_carte',
        ),
        migrations.CreateModel(
            name='MembreSecteurInformel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.membre')),
                ('secteurinformel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.secteurinformel')),
            ],
        ),
        migrations.CreateModel(
            name='MembreSecteurFemmeActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.membre')),
                ('secteurfemmeactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.secteurfemmeactive')),
            ],
        ),
        migrations.CreateModel(
            name='MembreSecteurAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField(blank=True, default=None, null=True, verbose_name="Date d'adhésion")),
                ('numero_carte', models.CharField(blank=True, max_length=250, null=True, verbose_name='N°Carte de membre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.membre')),
                ('secteuragricole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vieprofessionnelle.secteuragricole')),
            ],
        ),
        migrations.AddField(
            model_name='secteuragricole',
            name='membres',
            field=models.ManyToManyField(through='vieprofessionnelle.MembreSecteurAgricole', to='vieprofessionnelle.membre'),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='membres',
            field=models.ManyToManyField(through='vieprofessionnelle.MembreSecteurFemmeActive', to='vieprofessionnelle.membre'),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='membres',
            field=models.ManyToManyField(through='vieprofessionnelle.MembreSecteurInformel', to='vieprofessionnelle.membre'),
        ),
    ]
