# Generated by Django 4.1.1 on 2022-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0037_remove_secteuragricole_date_adhesion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='membre',
            name='contact',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numerobadge',
            field=models.CharField(default=None, max_length=250, unique=True, verbose_name='N°Badge'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numeropiece',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='N°de la pièce'),
        ),
    ]
