# Generated by Django 4.1.1 on 2022-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0038_remove_membre_adresse_alter_membre_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='numerobadge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, unique=True, verbose_name='N°Badge'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='qrcode',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, unique=True, verbose_name='QR Code'),
        ),
    ]
