# Generated by Django 4.1.1 on 2022-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0039_alter_membre_numerobadge_alter_membre_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='nom_prenoms',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250, null=True, verbose_name='Nom et prénoms'),
        ),
    ]
