# Generated by Django 4.1.1 on 2022-11-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0043_alter_etatsante_membre_alter_etatsante_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapeau', models.CharField(max_length=250, unique=True, verbose_name='Chapeau')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Contact')),
            ],
        ),
        migrations.AddField(
            model_name='secteuragricole',
            name='chapeau',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.chapeau'),
        ),
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='chapeau',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.chapeau'),
        ),
        migrations.AddField(
            model_name='secteurinformel',
            name='chapeau',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.chapeau'),
        ),
    ]
