# Generated by Django 4.1.1 on 2022-12-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_marche'),
        ('vieprofessionnelle', '0044_chapeau_secteuragricole_chapeau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteuragricole',
            name='chapeau',
        ),
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='chapeau',
        ),
        migrations.RemoveField(
            model_name='secteurinformel',
            name='chapeau',
        ),
        migrations.AlterField(
            model_name='secteurfemmeactive',
            name='marche',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.marche'),
        ),
    ]
