# Generated by Django 4.1.1 on 2022-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0048_membresecteuragricole_chapeau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='identifiant',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, unique=True, verbose_name='Identifiant'),
        ),
    ]
