# Generated by Django 4.1.1 on 2022-12-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0049_alter_membre_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='quartier',
        ),
    ]
