# Generated by Django 4.1.1 on 2022-12-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0010_marche'),
        ('vieprofessionnelle', '0050_remove_secteurfemmeactive_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteurfemmeactive',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.ville'),
        ),
    ]
