# Generated by Django 4.1.1 on 2022-12-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0052_remove_personneressource_chapeau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneressource',
            name='chapeau',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.chapeau'),
        ),
        migrations.AddField(
            model_name='personneressource',
            name='membre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vieprofessionnelle.membre'),
        ),
    ]
