# Generated by Django 4.1.1 on 2022-12-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vieprofessionnelle', '0054_secteuragricole_ville_secteurinformel_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteuragricole',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='secteuragricole',
            name='gps_longitude',
        ),
        migrations.RemoveField(
            model_name='secteuragricole',
            name='speculation_agricole',
        ),
        migrations.RemoveField(
            model_name='secteuragricole',
            name='superficie_en_culture',
        ),
        migrations.RemoveField(
            model_name='secteuragricole',
            name='superficie_en_production',
        ),
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='secteurfemmeactive',
            name='gps_longitude',
        ),
        migrations.RemoveField(
            model_name='secteurinformel',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='secteurinformel',
            name='gps_longitude',
        ),
        migrations.AddField(
            model_name='membresecteuragricole',
            name='gps_latitude',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='membresecteuragricole',
            name='gps_longitude',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='membresecteuragricole',
            name='superficie_en_culture',
            field=models.IntegerField(default=0, verbose_name='Superficie en culture'),
        ),
        migrations.AddField(
            model_name='membresecteuragricole',
            name='superficie_en_production',
            field=models.IntegerField(default=0, verbose_name='Superficie en production'),
        ),
        migrations.AddField(
            model_name='membresecteurfemmeactive',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='membresecteurfemmeactive',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='membresecteurinformel',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='membresecteurinformel',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPS Longitude'),
        ),
    ]
